version: '3.8'

services:
  app:
    image: ${DOCKERHUB_USERNAME}/github-actions-demo
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      REGION: ${REGION}
      JWT_SECRET: ${JWT_SECRET}
      SEND_EMAIL_PORT: ${SEND_EMAIL_PORT}
      SEND_EMAIL: ${SEND_EMAIL}
      SEND_EMAIL_PASSWORD: ${SEND_EMAIL_PASSWORD}

      hibernate_ddl_auto: update
      REDIS_HOST: redis
    logging:
      driver: awslogs
      options:
        awslogs-region: "ap-northeast-2"
        awslogs-group: "tavewebsite-log-group"
        awslogs-multiline-pattern: "^(INFO|ERROR)"
        awslogs-stream: "tavewebsite-backend-log"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
