version: '3.8'

services:
  app:
    image: ${DOCKERHUB_USERNAME}/github-actions-demo
    ports:
      - "8080:8080"
    env_file:
      - ./tave-website.env
    logging:
      driver: awslogs
      options:
        awslogs-region: "ap-northeast-2"
        awslogs-group: "tavewebsite-log-group"
        awslogs-multiline-pattern: "^(INFO|ERROR)"
        awslogs-stream: "tavewebsite-backend-log"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"