
version: '3.8'

services:
  app:
    image: ${DOCKERHUB_USERNAME}/github-actions-demo
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      REGION: ${REGION}
#      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      #       MAIL_USERNAME : ${MAIL_USERNAME}
      #       MAIL_PASSWORD : ${MAIL_PASSWORD}

      hibernate_ddl_auto: create
#      REDIS_HOST: redis
#    depends_on:
#      - redis

#  redis:
#    image: "redis:latest"
#    ports:
#      - "6379:6379"
