spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #      show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: never
      # mode: always
      schema-locations: classpath:org/springframework/batch/core/schema-postgresql.sql
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      #host: 127.0.0.1
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  mail:
    host: smtp.naver.com
    port: ${send_email_port}
    username: ${send_email}
    password: ${send_email_password}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com

  jwt:
    secret: ${JWT_SECRET}

cloud:
  aws:
    ses:
      username: ${ses_mail}
    credentials:
      access-key: ${access_key}
      secret-key: ${secret_key}
    s3:
      bucket: ${bucket_name}
    region:
      static: ${region}

final_interview_form: ${FINAL_INTERVIEW_FORM}
interview_possible_time_table: ${INTERVIEW_POSSIBLE_TIME_TABLE_XLSX}
interview_time_table_for_manager: ${INTERVIEW_TIME_TABLE_FOR_MANAGER}

logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            PreparedStatementCreator: OFF
            JdbcTemplate$SimplePreparedStatementCreator: OFF
#  org.hibernate.type: trace
