spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/taveWebsite
    username: sa
    password: 1111
  #    driver-class-name: org.postgresql.Driver
#    url: ${DB_URL}
#    username: ${USERNAME}
#    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #      show_sql: true
        format_sql: true
  data:
    redis:
      port: 6379
      host: redis
  #      host: 127.0.0.1

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  mail:
    host: smtp.naver.com
    port: ${send_email_port}
    username: ${send_email}
    password: ${send_email_password}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com

  jwt:
    secret: ${JWT_SECRET}

cloud:
  aws:
    credentials:
      access-key: ${access-key}
      secret-key: ${secret-key}
    s3:
      bucket: ${bucket_name}
    region:
      static: ${region}

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

