spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/tave;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

cloud:
  aws:
    credentials:
      access-key: ${access_key}
      secret-key: ${secret_key}
    s3:
      bucket: ${bucket_name}
    region:
      static: ${region}

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
